### ISSUE TITLE
Your endpoint may have encountered an unexpected error, and I am unable to access your service.Hope you can fix it.

### ISSUE THREAD

**Issue by 421333** [hypergrok/chunkit#1]
Your endpoint may have encountered an unexpected error, and I am unable to access your service.Hope you can fix it.

**Comment by hypergrok** [comment]
Hello, thank you for your feedback. Can you please paste: 

1) The code you are trying to run
2) Which URL you are trying to chunk
3) The exact error message you are getting

Thanks

**Comment by hypergrok** [comment]
Hello, the bug has been patched. If it happens again, please reopen this issue with the code to reproduce it. Thank you.

**Comment by 421333** [comment]
Hi there,
Thanks for fixing the bug! If it happens again, I’ll make sure to reopen the issue with the code needed to reproduce it.
Thanks again!
